service: node-simple-http-endpoint

provider:
  name: google
  runtime: nodejs18
  project: useful-ward-464800-t5
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  recebeAtividade:
    handler: recebeAtividade
    events:
      - http: path
  insereAtividade:
    handler: insereAtividade
    events:
      - event:
          eventType: google.pubsub.topic.publish
          resource: projects/${self:provider.project}/topics/atividades